/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControllerViewDados;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;
import model.Clima;
import model.Observer;

/**
 *
 * @author jose
 */
public class ViewDados extends javax.swing.JFrame implements Observer, ActionListener {

    /**
     * Creates new form ViewDados
     */
    
    private Clima model;
    private ControllerViewDados controller;
    public ViewDados(Clima model) {
        initComponents();
        
        this.model=model;
        this.controller= new ControllerViewDados(this.model, this);
        this.model.attach(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_addTempo = new javax.swing.JButton();
        btn_addTemperatura = new javax.swing.JButton();
        btn_addUf = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_Temperatura = new javax.swing.JTextField();
        txt_addTempo = new javax.swing.JTextField();
        txt_addUf = new javax.swing.JTextField();
        btn_addCidade = new javax.swing.JButton();
        txt_addCidade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        btn_addTempo.setText("Add Tempo");
        btn_addTempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addTempoActionPerformed(evt);
            }
        });

        btn_addTemperatura.setText("Add temperatura");
        btn_addTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addTemperaturaActionPerformed(evt);
            }
        });

        btn_addUf.setText("Add UF");
        btn_addUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addUfActionPerformed(evt);
            }
        });

        jLabel1.setText("FUNCEME");

        txt_addTempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addTempoActionPerformed(evt);
            }
        });

        btn_addCidade.setText("Add cidade");
        btn_addCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addCidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_addCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_addUf, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addComponent(txt_addTempo, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_Temperatura, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_addCidade)
                            .addComponent(btn_addTempo)
                            .addComponent(btn_addTemperatura)
                            .addComponent(btn_addUf))))
                .addGap(0, 140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_addCidade)
                    .addComponent(txt_addCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_addTemperatura))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_addTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_addTempo))
                .addGap(18, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_addUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_addUf))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addUfActionPerformed
        // TODO add your handling code here:
        controller.trataBotao(evt);

    }//GEN-LAST:event_btn_addUfActionPerformed

    private void txt_addTempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addTempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addTempoActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_formMouseClicked

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    private void btn_addTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addTemperaturaActionPerformed
        // TODO add your handling code here:
        controller.trataBotao(evt);
       
    }//GEN-LAST:event_btn_addTemperaturaActionPerformed

    private void btn_addTempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addTempoActionPerformed
        // TODO add your handling code here:
                controller.trataBotao(evt);

    }//GEN-LAST:event_btn_addTempoActionPerformed

    private void btn_addCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addCidadeActionPerformed
        // TODO add your handling code here:
                controller.trataBotao(evt);

    }//GEN-LAST:event_btn_addCidadeActionPerformed

    /**
     * @param args the command line arguments
     */
  /*  public static void main(String args[]) {
        /
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addCidade;
    private javax.swing.JButton btn_addTemperatura;
    private javax.swing.JButton btn_addTempo;
    private javax.swing.JButton btn_addUf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt_Temperatura;
    private javax.swing.JTextField txt_addCidade;
    private javax.swing.JTextField txt_addTempo;
    private javax.swing.JTextField txt_addUf;
    // End of variables declaration//GEN-END:variables
    
    
    
    
    @Override
    public void update() {
            
        
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        
        System.out.println("Hellloooo");
       this.controller.trataBotao(e);
    }

    public JTextField getTxt_Temperatura() {
        return txt_Temperatura;
    }

    public void setTxt_Temperatura(JTextField txt_Temperatura) {
        this.txt_Temperatura = txt_Temperatura;
    }

    public JTextField getTxt_addCidade() {
        return txt_addCidade;
    }

    public void setTxt_addCidade(JTextField txt_addCidade) {
        this.txt_addCidade = txt_addCidade;
    }

    

    public JTextField getTxt_addTempo() {
        return txt_addTempo;
    }

    public void setTxt_addTempo(JTextField txt_addTempo) {
        this.txt_addTempo = txt_addTempo;
    }

    public JTextField getTxt_addUf() {
        return txt_addUf;
    }

    public void setTxt_addUf(JTextField txt_addUf) {
        this.txt_addUf = txt_addUf;
    }

   
    
}
