/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControllerViewMesaDois;
import model.Servidor;
import model.Observer;

/**
 *
 * @author jose
 */
public class ViewMesaDois extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form ViewMesaDois
     */
    private Servidor model;
    private ControllerViewMesaDois controller;

    public ViewMesaDois(Servidor model) {
        initComponents();
        this.model = model;
        this.controller = new ControllerViewMesaDois(this.model, this);
        this.model.attach(this);
        this.Sol.setVisible(false);
        //  this.Indeterminado.setVisible(false);
        this.chuva.setVisible(false);
        this.Nublado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Cidade = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Sol = new javax.swing.JLabel();
        Nublado = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Temperatura = new javax.swing.JLabel();
        Indeterminado = new javax.swing.JLabel();
        chuva = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Tempo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        Cidade.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Cidade.setText("CIDADE");
        getContentPane().add(Cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setText("Temperatura");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 310, -1));

        Sol.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Sol.setIcon(new javax.swing.ImageIcon("/home/jose/NetBeansProjects/ExemploMVC/Hello/1.png")); // NOI18N
        Sol.setToolTipText("");
        getContentPane().add(Sol, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        Nublado.setIcon(new javax.swing.ImageIcon("/home/jose/NetBeansProjects/ExemploMVC/Hello/2.png")); // NOI18N
        getContentPane().add(Nublado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel6.setText("º");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        Temperatura.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Temperatura.setText("0.00");
        getContentPane().add(Temperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        Indeterminado.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Indeterminado.setForeground(new java.awt.Color(255, 0, 0));
        Indeterminado.setText("Indeterminado");
        getContentPane().add(Indeterminado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        chuva.setIcon(new javax.swing.ImageIcon("/home/jose/NetBeansProjects/ExemploMVC/Hello/3.png")); // NOI18N
        getContentPane().add(chuva, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cidade;
    private javax.swing.JLabel Indeterminado;
    private javax.swing.JLabel Nublado;
    private javax.swing.JLabel Sol;
    private javax.swing.JLabel Temperatura;
    private javax.swing.JLabel chuva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        this.Cidade.setText(this.model.getCidade());
        this.Temperatura.setText(Float.toString(this.model.getTemperatura()));
        if ("Nublado".equals(model.getTempo())) {
            this.Sol.setVisible(false);
            this.Indeterminado.setVisible(false);
            this.chuva.setVisible(false);
            this.Nublado.setVisible(true);
        } else if ("Sol".equals(model.getTempo())) {
            this.Sol.setVisible(true);
            
            this.chuva.setVisible(false);
            this.Indeterminado.setVisible(false);
            this.Nublado.setVisible(false);
        } else if ("Chuvoso".equals(model.getTempo())) {
            this.Sol.setVisible(false);
            this.chuva.setVisible(true);
            this.Indeterminado.setVisible(false);
            this.Nublado.setVisible(false);
        } else {

            this.Sol.setVisible(false);
            this.Indeterminado.setVisible(true);
            this.Nublado.setVisible(false);
            this.chuva.setVisible(false);

        }

    }
}
