/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControllerViewMesa;
import model.Servidor;
import model.Observer;

/**
 *
 * @author jose
 */
public class ViewMesa extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form ViewMesa
     * 
     */
    
    private Servidor model;
    private ControllerViewMesa controller;
    
    public ViewMesa(Servidor model) {
        initComponents();
        this.model=model;
        this.controller= new ControllerViewMesa(model, this);
        this.model.attach(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_RTemperatura = new javax.swing.JLabel();
        txt_RCidade = new javax.swing.JLabel();
        txt_RUf = new javax.swing.JLabel();
        txt_RTempo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Temperatura:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Cidade:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("UF:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Tempo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText(" RESULTADO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        txt_RTemperatura.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txt_RTemperatura.setText(" 00");
        getContentPane().add(txt_RTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        txt_RCidade.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txt_RCidade.setText("Desconhecida");
        getContentPane().add(txt_RCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, 20));

        txt_RUf.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txt_RUf.setText("Desconhecido");
        getContentPane().add(txt_RUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        txt_RTempo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txt_RTempo.setText("Desconhecido");
        getContentPane().add(txt_RTempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("/home/jose/NetBeansProjects/ExemploMVC/Hello/4.png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    //OLHA AQUI
    /*public static void main(String args[]) {
       
      
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel txt_RCidade;
    private javax.swing.JLabel txt_RTemperatura;
    private javax.swing.JLabel txt_RTempo;
    private javax.swing.JLabel txt_RUf;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        
        this.txt_RCidade.setText(model.getCidade());
        this.txt_RTemperatura.setText(Float.toString(model.getTemperatura()));
        this.txt_RTempo.setText(model.getTempo());
        this.txt_RUf.setText(model.getUf());
        
    }
}
